# Generated by Django 2.2.7 on 2019-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('byline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('batch', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
