# Generated by Django 2.2.7 on 2020-03-22 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200321_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='display',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
