# Generated by Django 2.2.20 on 2021-04-26 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210425_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='batch',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
