# Generated by Django 3.2.4 on 2021-06-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210601_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_credits',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
