# Generated by Django 3.2.4 on 2021-07-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210621_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
